author: Nicholas Valentinus
nics_ver: 3.0.0

baseurl: /now-i-can-sleep
url: https://nvfp.github.io

include: 
  - _sass
  - _scripts
  - pages
exclude: 
  - readme.md

sass:
  style: compact
  sass_dir: _sass
