

# website

baseurl: /now-i-can-sleep
url: https://nvfp.github.io/now-i-can-sleep


# personal

title: now-i-can-sleep
author:
  name: Nicholas Valentinus


# internal

include: [_pages, _sass, scripts]

permalink: pretty

sass:
  style: compact # possible values: nested expanded compact compressed
  sass_dir: _sass
