name: now-i-can-sleep
description: Automatically build GitHub documentation.

inputs:
  src:
    description: The relative path (relative to the root) to the folder containing the documentation files.
    required: false
    default: ./docs
  author:
    description: Author
    required: true
  analytics:
    description: Google Analytics tracking ID
    required: false
    default: null

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: python $GITHUB_ACTION_PATH/nics
      env:
        IPT_SRC: ${{ inputs.src }}
        IPT_AUTHOR: ${{ inputs.author }}
        IPT_ANALYTICS: ${{ inputs.analytics }}
        IPT_ACTION_REF: ${{ github.action_ref }}
      shell: bash

    ## Build the static files
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - run: gem install bundler && bundle install  # Install dependencies
      shell: bash
    - run: bundle exec jekyll build  # Build Jekyll site
      shell: bash

    ## Debug
    - run: find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
      shell: bash
    - run: find ./_site | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
      shell: bash


    ## Note that the process of uploading artifacts below is actually not needed,
    ## but i dont know how to use `actions/deploy-pages@v2` without the artifact process.
    ## soon the method below should get improved.

    ## Upload the _site as artifact
    - uses: actions/upload-pages-artifact@v2

    ## Deploy to GitHub Pages
    - uses: actions/deploy-pages@v2



author: Nicholas Valentinus
branding:
  icon: settings
  color: red
