name: now-i-can-sleep
description: Automatically build GitHub documentation.

inputs:
  nics_docs_dir_relpth:
    description: The relative path (relative to the root) to the folder containing the documentation files.
    required: true
    default: ./docs

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'    
    - run: echo pwd
      shell: bash
    - run: python nics
      shell: bash



author: Nicholas Valentinus
branding:
  icon: settings
  color: red
