title: Proto Abc 123 Xyz foo bar baz
desc: My test desc
author: Nicholas Valentinus
analytics: G-G3HERGXF6P  # Google Analytics tracking ID
nics_ver: 1.2.3

baseurl: /nics
url: https://nvfp.github.io

include: [_sass]
sass: {style: compressed, sass_dir: _sass, sourcemap: never}
