title: Proto
desc: My test desc
author: Nicholas Valentinus
google_analytics_tracking_id: G-G3HERGXF6P
nics_ver: 3.0.0

baseurl: /now-i-can-sleep
url: https://nvfp.github.io

include: [_sass]
sass: {style: compact, sass_dir: _sass}
