

# website

baseurl: /mykit
url: https://nvfp.github.io/mykit


# personal

title: mykit
author:
  name: Nicholas Valentinus


# internal

include: [_pages, _sass, scripts]

permalink: pretty

sass:
  style: compact # possible values: nested expanded compact compressed
  sass_dir: _sass