name: Trigger remote test

on:
  # Note: it will also run when 'fast-pypi-release' is completed at only
  #       the first job 'check-commit-msg' (aka not a trigger commit).
  workflow_run:
    workflows: [Fast PyPI release]
    types:
      - completed
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.NICS_REMOTE_TEST_WORKFLOW_PAT_TOKEN }}  # Note, PAT token needs to be updated if it has expired
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'nvfp',
              repo: 'demo-testing',
              workflow_id: 'NICS-remote-testing.yml',
              ref: 'main'
            })
